//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentFee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Payment
    {
        public int Id { get; set; }
        public int Student_Id { get; set; }
        public int Subject_Id { get; set; }
        public double First_Installment { get; set; }
        public double Second_Installment { get; set; }
        public int Status { get; set; }
    }
}
